### ISSUE TITLE
Doesn't run under Linux

### ISSUE THREAD

**Issue by teymuri** [lgvr123/musescore-durationeditor#2]
Your plugin doesn't appear or seem to have any effects when I click `Run plugin durationeditor`. I am using MS4 on Lubuntu Linux.

**Comment by lgvr123** [comment]
Unfortunately this plugin (as many other ones) does not work with MS4.0.

There are many things that the MuseScore team has not ported yet from Musescore 3.6 to Musescore 4.0 ([full list here](https://musescore.org/en/node/334701)). The plugin API is one of those non ported/non adapted features.

So, while the basic plugin are working in MS4, most plugin dealing with score manipulations, reading/writing scores, dock-type plugin, ...  are no simply not working.

For now, the MS team has not provided any planning for reviewing the plugin mechanism (should be done for MS4.1). There is nothing we can do about that. That's the reason why I stick ([as many other users](https://musescore.org/en/node/344707)) to 3.6.

Sorry that I could not help with this. As soon as the MS4 plugin mechanism is reviewed I'll adapt this plugin. Be sure to "Watch" that repository to stay informed.

Cheers.
