### ISSUE TITLE
How to untriplet triplets?

### ISSUE THREAD

**Issue by riverpaper** [lgvr123/musescore-durationeditor#4]
Hi, I've tried using your plugin and I think I'm doing something wrong because none of the buttons are working. The plugin window thing opens fine, but nothing happens when I press the buttons except for a `Warning - Tuplet conversion: Invalid selection` message when the wrong thing is selected. This isn't the problem because it doesn't appear when I select the right thing, but it still doesn't convert the triplet.

I'm using MuseScore 3 and Duration Editor v1.3.0.

**Comment by lgvr123** [comment]
Hi, Thanks for reporting this issue. Can you post a picture of the selection you're doing and which causes this issue ?
Sure to be sure: are you using either MU3.6(.2) or MU3.7 ?

**Comment by riverpaper** [comment]
It's strange because all the buttons are dead and unresponsive, on all of my scores. This leads me to believe I must have installed it wrong or something. Here's an example selection of where I would press the tuplet button, except nothing changes.

![image](https://github.com/lgvr123/musescore-durationeditor/assets/50542928/a4108d60-e3a8-4f65-b070-f1f1f9183eb5)

```
OS: Windows 10 (10.0)
Arch.: x86_64
MuseScore version (64-bit): 3.3.4.9134
revision: github-musescore-musescore-7ea61d9
```

**Comment by riverpaper** [comment]
But also, I don't see how I could have installed it wrong, and it still runs?

![image](https://github.com/lgvr123/musescore-durationeditor/assets/50542928/c453bae9-5da0-4744-993a-39bde02b152a)

**Comment by lgvr123** [comment]
> 3.3.4.9134

This is a pretty old version !!! 
I advise you test it with latest 3.6 official version 3.6.2
Or the unofficial latest 3 version, the [3.7](https://github.com/Jojo-Schmitz/MuseScore).
I close the issue. If after having installed either 3.6.2 or 3.7 the issue persists, feel free to reopen it.

**Comment by riverpaper** [comment]
Sorry for wasting your time, it works with `MuseScore version (32-bit): 3.6.2.548021803`.
